### ISSUE TITLE
minor frontend changes

### ISSUE THREAD

**Issue by ptsdpatient** [ShiwangPande/Noteboard-backend#1]
### **taking out scale effect on hover for text area and input tag**

![image](https://github.com/user-attachments/assets/1c48490e-de8c-4cfc-9634-31516c2f747f)

### **horizontal layout for desktop user accessibility :**

![image](https://github.com/user-attachments/assets/6cf3850b-fb45-400f-b309-fc155f3cddbc)

**Comment by ShiwangPande** [comment]
ok
